### PR TITLE
Fixed dependency of website_sale_payment.

### PR DESCRIPTION
**Pull request by manengel**
This PR is for the fixed revision of website_sale_payment. A prior undeclared dependency to stock_picking_on_hold is now included.

### CODE REVIEW

**Comment by jans23** [comment]
All changes in this repo odoo-temp should be copies of changes from the original repositories. In this case I don't see that you changed the original repository.

**Comment by manengel** [comment]
> All changes in this repo odoo-temp should be copies of changes from the original repositories. In this case I don't see that you changed the original repository.

This commit is essentially a mimic of https://github.com/Nitrokey/odoo-sale-workflow/commit/c93ea8411f79f49454d820a5fca455c316e83226

**Comment by jans23** [comment]
Right. Sorry I missed that. The referenced commit fails (the CI). Do you still want to have this merged?

**Comment by manengel** [comment]
In the case of odoo-temp, sure. For the other PR I need to understand how you can include other repositories into the check as there is now a dependency the CI there does not know how to handle.

**Pull request merged**
